const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  minimize: () => ipcRenderer.send('window-minimize'),
  maximize: () => ipcRenderer.send('window-maximize'),
  close: () => ipcRenderer.send('window-close'),
  onNewTab: (callback) => ipcRenderer.on('shortcut-new-tab', () => callback()),
  onNewPrivateTab: (callback) => ipcRenderer.on('shortcut-new-private-tab', () => callback()),
  onNewWindow: (callback) => ipcRenderer.on('shortcut-new-window', () => callback()),
  onCloseTab: (callback) => ipcRenderer.on('shortcut-close-tab', () => callback()),
  onDownloadUpdate: (callback) => ipcRenderer.on('download-update', (event, downloadItem) => callback(downloadItem)),
  onOpenLinkNewTab: (callback) => ipcRenderer.on('open-link-new-tab', (event, url) => callback(url)),
  showContextMenu: (params) => ipcRenderer.send('show-context-menu', params),
  onContextMenuAction: (callback) => ipcRenderer.on('context-menu-action', (event, action, x, y) => callback(action, x, y)),
  onFind: (callback) => ipcRenderer.on('shortcut-find', () => callback()),
  onCycleTabPrev: (callback) => ipcRenderer.on('shortcut-cycle-tab-prev', () => callback()),
  onCycleTabNext: (callback) => ipcRenderer.on('shortcut-cycle-tab-next', () => callback()),
  onJumpTab: (callback) => ipcRenderer.on('shortcut-jump-tab', (event, index) => callback(index)),
  onFocusAddress: (callback) => ipcRenderer.on('shortcut-focus-address', () => callback()),
  onReload: (callback) => ipcRenderer.on('shortcut-reload', () => callback()),
  onDevTools: (callback) => ipcRenderer.on('shortcut-devtools', () => callback()),
  onOpenHistory: (callback) => ipcRenderer.on('shortcut-open-history', () => callback()),
  onOpenDownloads: (callback) => ipcRenderer.on('shortcut-open-downloads', () => callback()),
  onOpenBookmarks: (callback) => ipcRenderer.on('shortcut-open-bookmarks', () => callback()),
  onZoomIn: (callback) => ipcRenderer.on('shortcut-zoom-in', () => callback()),
  onZoomOut: (callback) => ipcRenderer.on('shortcut-zoom-out', () => callback()),
  onZoomReset: (callback) => ipcRenderer.on('shortcut-zoom-reset', () => callback()),
  onCommandPalette: (callback) => ipcRenderer.on('shortcut-command-palette', () => callback()),
  onRestoreTab: (callback) => ipcRenderer.on('shortcut-restore-tab', () => callback()),
  onToggleBookmarksBar: (callback) => ipcRenderer.on('shortcut-toggle-bookmarks-bar', () => callback()),
  onOpenSettings: (callback) => ipcRenderer.on('shortcut-open-settings', () => callback()),
  onViewSource: (callback) => ipcRenderer.on('shortcut-view-source', () => callback()),
  onPrint: (callback) => ipcRenderer.on('shortcut-print', () => callback()),
  onAddBookmark: (callback) => ipcRenderer.on('shortcut-add-bookmark', () => callback()),
  onTabCrashed: (callback) => ipcRenderer.on('tab-crashed', (event, webContentsId, reason) => callback(webContentsId, reason)),
  onAppCommand: (callback) => ipcRenderer.on('app-command', (event, cmd) => callback(cmd)),
  openFile: (path) => ipcRenderer.send('open-file', path),
  showInFolder: (path) => ipcRenderer.send('show-in-folder', path),
  setAdBlocker: (enabled) => ipcRenderer.send('set-adblocker', enabled),
  updateSettings: (settings) => ipcRenderer.send('update-settings', settings),
  onAdBlocked: (callback) => ipcRenderer.on('ad-blocked', (event, webContentsId, category) => callback(webContentsId, category)),

  onOpenPdfViewer: (callback) => ipcRenderer.on('open-pdf-viewer', (event, url, webContentsId) => callback(url, webContentsId)),
  fetchPdf: (url) => ipcRenderer.invoke('fetch-pdf', url),
  clearCache: () => ipcRenderer.send('clear-cache'),
  getPermissions: () => ipcRenderer.invoke('get-permissions'),
  deletePermission: (origin, permission) => ipcRenderer.send('delete-permission', origin, permission),
  clearPermissions: () => ipcRenderer.send('clear-permissions'),
  cancelDownload: (id) => ipcRenderer.send('cancel-download', id),
  pauseDownload: (id) => ipcRenderer.send('pause-download', id),
  resumeDownload: (id) => ipcRenderer.send('resume-download', id),
  openPrivateWindow: () => ipcRenderer.send('open-private-window'),
  openNewWindow: () => ipcRenderer.send('open-new-window'),
  loadExtension: () => ipcRenderer.invoke('load-extension'),
  getExtensions: () => ipcRenderer.invoke('get-extensions'),
  setExtensionEnabled: (id, enabled) => ipcRenderer.invoke('set-extension-enabled', id, enabled),
  removeExtension: (id) => ipcRenderer.invoke('remove-extension', id),
  getPlugins: () => ipcRenderer.invoke('get-plugins'),
  registerPlugin: (plugin) => ipcRenderer.invoke('register-plugin', plugin),
  setPluginEnabled: (id, enabled) => ipcRenderer.invoke('set-plugin-enabled', id, enabled),
  removePlugin: (id) => ipcRenderer.invoke('remove-plugin', id),
  getPassword: (origin) => ipcRenderer.invoke('get-password', origin),
  getAllPasswords: () => ipcRenderer.invoke('get-all-passwords'),
  savePassword: (origin, creds) => ipcRenderer.send('save-password', origin, creds),
  deletePassword: (origin) => ipcRenderer.send('delete-password', origin),
  saveAsPdf: () => ipcRenderer.send('save-as-pdf'),
  onTriggerSaveAsPdf: (callback) => ipcRenderer.on('trigger-save-as-pdf', () => callback()),
  executeSavePdf: (data) => ipcRenderer.send('execute-save-pdf', data),
  fetchSuggestions: (query) => ipcRenderer.invoke('fetch-suggestions', query),
  getUpdateStatus: () => ipcRenderer.invoke('get-update-status'),
  checkForUpdates: () => ipcRenderer.invoke('check-for-updates'),
  downloadUpdate: () => ipcRenderer.invoke('download-update'),
  installUpdate: () => ipcRenderer.invoke('install-update'),
  onUpdateStatus: (callback) => ipcRenderer.on('update-status', (event, status) => callback(status))
});
